// mockData.js
export const sales = [
  {
    id: 1,
    date: "2023-06-15",
    invoiceNumber: 100001,
    clientName: "John Smith",
    clientPhone: "555-0101",
    items: [
      {
        id: 1,
        name: "Amoxicillin 250mg",
        price: 3.5,
        quantity: 2,
        costPrice: 1.2,
      },
      {
        id: 3,
        name: "Surgical Gloves (Medium)",
        price: 18.0,
        quantity: 1,
        costPrice: 12.0,
      },
    ],
    paymentMethod: "card",
    taxRate: 8,
    discount: 0,
    subtotal: 25.0,
    tax: 2.0,
    totalAmount: 27.0,
    notes: "Prescription given for antibiotics",
    lastUpdated: "2023-06-15T14:30:00Z",
  },
  {
    id: 2,
    date: "2023-06-10",
    invoiceNumber: 100002,
    clientName: "Sarah Johnson",
    clientPhone: "555-0102",
    items: [
      {
        id: 2,
        name: "Rabies Vaccine",
        price: 25.0,
        quantity: 1,
        costPrice: 8.75,
      },
      {
        id: 4,
        name: "Dog Food (Premium)",
        price: 65.0,
        quantity: 1,
        costPrice: 35.0,
      },
    ],
    paymentMethod: "cash",
    taxRate: 8,
    discount: 5.0,
    subtotal: 90.0,
    tax: 7.2,
    totalAmount: 92.2,
    notes: "Annual vaccination and food purchase",
    lastUpdated: "2023-06-10T11:15:00Z",
  },
];

// export const inventoryItems = [
//   {
//     id: 1,
//     name: "Amoxicillin 250mg",
//     description: "Broad-spectrum antibiotic for bacterial infections",
//     category: "Medication",
//     manufacturer: "PetPharma Inc.",
//     supplier: "VetSupply Co.",
//     batchNumber: "AMX-2023-05-001",
//     expiryDate: "2024-11-30",
//     quantity: 42,
//     unit: "tablets",
//     costPrice: 1.2,
//     sellingPrice: 3.5,
//     mrp: 4.0,
//     lowStockThreshold: 10,
//     taxRate: 5,
//     location: "Pharmacy",
//     notes: "Keep in dry place",
//     lastUpdated: "2023-06-15T09:30:00Z",
//     profit: 2.3,
//     profitPercentage: 191.67,
//   },
// ];

export const vaccinations = [
  {
    id: 1,
    clientId: 1,
    petName: "Buddy",
    vaccineName: "Rabies",
    dateAdministered: "2025-04-01",
    nextDueDate: "2026-04-01",
  },
  {
    id: 2,
    clientId: 2,
    petName: "Whiskers",
    vaccineName: "Feline Distemper",
    dateAdministered: "2025-03-15",
    nextDueDate: "2025-09-15",
  },
];

export const appointments = [
  {
    id: 1,
    clientId: 1,
    clientName: "Sugam Bastola",
    petName: "Buddy",
    petType: "Dog",
    date: "2025-06-15",
    time: "10:30",
    reason: "Regular Checkup",
    contactNumber: "555-1234",
    notes: "Follow up after 6 months",
    vetName: "Dr. Smith",
    followUpDate: "2025-12-15",
    priority: "Normal",
    completed: false,
  },
  {
    id: 4,
    clientId: 1,
    clientName: "Sugam Bastola",
    petName: "Buddy",
    petType: "Dog",
    date: "2025-06-15",
    time: "10:30",
    reason: "Regular Checkup",
    contactNumber: "555-1234",
    notes: "Follow up after 6 months",
    vetName: "Dr. Smith",
    followUpDate: "2025-12-15",
    priority: "Normal",
    completed: false,
  },
  {
    id: 3,
    clientId: 1,
    clientName: "Sugam Bastola",
    petName: "Buddy",
    petType: "Dog",
    date: "2025-06-15",
    time: "10:30",
    reason: "Regular Checkup",
    contactNumber: "555-1234",
    notes: "Follow up after 6 months",
    vetName: "Dr. Smith",
    followUpDate: "2025-12-15",
    priority: "Normal",
    completed: false,
  },
  {
    id: 2,
    clientId: 2,
    clientName: "Sugam Bastola",
    petName: "Whiskers",
    petType: "Cat",
    date: "2025-06-20",
    time: "14:00",
    reason: "Vaccination",
    contactNumber: "555-5678",
    notes: "Ensure rabies shot updated",
    vetName: "Dr. Brown",
    followUpDate: "2025-12-20",
    priority: "Urgent",
    completed: true,
  },
];

export const inventoryItems = [
  {
    id: 1,
    name: "Amoxicillin 250mg",
    description: "Broad-spectrum antibiotic for bacterial infections",
    category: "Medication",
    manufacturer: "PetPharma Inc.",
    supplier: "VetSupply Co.",
    batchNumber: "AMX-2023-05-001",
    expiryDate: "2024-11-30",
    quantity: 42,
    unit: "tablets",
    costPrice: 1.2,
    sellingPrice: 3.5,
    mrp: 4.0,
    lowStockThreshold: 10,
    taxRate: 5,
    location: "Pharmacy",
    notes: "Keep in dry place",
    lastUpdated: "2023-06-15T09:30:00Z",
    profit: 2.3,
    profitPercentage: 191.67,
  },
  {
    id: 2,
    name: "Rabies Vaccine",
    description: "Single dose rabies vaccine for dogs and cats",
    category: "Vaccine",
    manufacturer: "AnimalHealth Ltd.",
    supplier: "MediVet Distributors",
    batchNumber: "RBV-2023-04-012",
    expiryDate: "2024-04-30",
    quantity: 18,
    unit: "vials",
    costPrice: 8.75,
    sellingPrice: 25.0,
    mrp: 28.0,
    lowStockThreshold: 5,
    taxRate: 5,
    location: "Main Storage",
    notes: "Store refrigerated",
    lastUpdated: "2023-06-10T14:15:00Z",
    profit: 16.25,
    profitPercentage: 185.71,
  },
  {
    id: 3,
    name: "Surgical Gloves (Medium)",
    description: "Sterile latex surgical gloves, box of 100",
    category: "Surgical Item",
    manufacturer: "SafeTouch Medical",
    supplier: "Surgical Supplies Inc.",
    batchNumber: "GLV-2023-03-105",
    expiryDate: "2025-03-31",
    quantity: 3,
    unit: "boxes",
    costPrice: 12.0,
    sellingPrice: 18.0,
    mrp: 20.0,
    lowStockThreshold: 2,
    taxRate: 5,
    location: "Surgery Room",
    notes: "Latex free available on request",
    lastUpdated: "2023-06-05T11:45:00Z",
    profit: 6.0,
    profitPercentage: 50.0,
  },
  {
    id: 4,
    name: "Dog Food (Premium)",
    description: "High-quality adult dog food, 15kg bag",
    category: "Food",
    manufacturer: "PetNutrition Co.",
    supplier: "PetFood Distributors",
    batchNumber: "DFD-2023-06-008",
    expiryDate: "2024-06-30",
    quantity: 0,
    unit: "bags",
    costPrice: 35.0,
    sellingPrice: 65.0,
    mrp: 70.0,
    lowStockThreshold: 3,
    taxRate: 5,
    location: "Front Office",
    notes: "Best seller - reorder soon",
    lastUpdated: "2023-06-18T16:20:00Z",
    profit: 30.0,
    profitPercentage: 85.71,
  },
];

export const medicalRecords = [
  {
    id: 1,
    date: "2025-04-01",
    patientId: "P12345",
    patientName: "Buddy",
    patientType: "Dog",
    ownerName: "John Doe",
    veterinarian: "Dr. Emily Clark",
    diagnosis: "Routine Checkup",
    treatment: "Vaccination and dental cleaning",
    medications: [
      {
        name: "CanineVax",
        dosage: "2ml",
        frequency: "Once",
        duration: "Single dose",
        notes: "Administered during visit",
      },
    ],
    notes: "Healthy dog, no concerns.",
    followUpDate: "2025-06-01",
    status: "active",
    lastUpdated: "2025-04-01T10:00:00Z",
  },
  {
    id: 2,
    date: "2025-04-15",
    patientId: "P67890",
    patientName: "Whiskers",
    patientType: "Cat",
    ownerName: "Jane Smith",
    veterinarian: "Dr. Michael Lee",
    diagnosis: "Feline asthma",
    treatment: "Inhaled corticosteroids prescribed",
    medications: [
      {
        name: "Fluticasone",
        dosage: "100 mcg",
        frequency: "Twice daily",
        duration: "30 days",
        notes: "Monitor respiratory function",
      },
    ],
    notes: "Observe for any breathing difficulty.",
    followUpDate: "2025-05-15",
    status: "monitoring",
    lastUpdated: "2025-04-15T15:30:00Z",
  },
  // Add more records as needed
];
// mockData.js

export const staffMembers = [
  {
    id: 1,
    fullName: "Dr. Emily Carter",
    role: "Veterinarian",
    licenseNumber: "VET-12345",
    qualifications: "DVM, MSc Veterinary Surgery",
    phone: "555-123-4567",
    email: "emily.carter@vetclinic.com",
    joinDate: "2021-08-15",
    address: "123 Pet Street, Springfield",
    emergencyContact: "John Carter - 555-987-6543",
    notes: "Specializes in small animal surgery.",
    active: true,
  },
  {
    id: 2,
    fullName: "Sarah Johnson",
    role: "Nurse",
    licenseNumber: "NUR-45678",
    qualifications: "BSc Veterinary Nursing",
    phone: "555-234-5678",
    email: "sarah.johnson@vetclinic.com",
    joinDate: "2022-01-10",
    address: "456 Animal Ave, Springfield",
    emergencyContact: "Mike Johnson - 555-321-8765",
    notes: "Handles post-op care and vaccinations.",
    active: true,
  },
  {
    id: 3,
    fullName: "Tom Rivera",
    role: "Technician",
    licenseNumber: "TECH-78901",
    qualifications: "Certified Vet Technician",
    phone: "555-345-6789",
    email: "tom.rivera@vetclinic.com",
    joinDate: "2020-05-22",
    address: "789 Paw Lane, Springfield",
    emergencyContact: "Anna Rivera - 555-654-3210",
    notes: "Expert in diagnostic equipment.",
    active: false,
  },
  {
    id: 4,
    fullName: "Jessica Lane",
    role: "Receptionist",
    licenseNumber: "",
    qualifications: "Diploma in Office Management",
    phone: "555-456-7890",
    email: "jessica.lane@vetclinic.com",
    joinDate: "2023-03-05",
    address: "321 Cat Blvd, Springfield",
    emergencyContact: "Sarah Lane - 555-765-4321",
    notes: "Manages front desk and appointment bookings.",
    active: true,
  },
  {
    id: 5,
    fullName: "Mark Lee",
    role: "Admin",
    licenseNumber: "",
    qualifications: "MBA in Healthcare Admin",
    phone: "555-567-8901",
    email: "mark.lee@vetclinic.com",
    joinDate: "2019-11-30",
    address: "987 Dogwood Dr, Springfield",
    emergencyContact: "Lisa Lee - 555-543-2109",
    notes: "Oversees clinic operations and staff.",
    active: true,
  },
];
export const suppliers = [
  {
    id: 1,
    name: "John Supplier",
    company: "PetCare Supplies Inc.",
    phone: "123-456-7890",
    email: "john@petcare.com",
    address: "123 Main St, Springfield",
  },
  {
    id: 2,
    name: "Lisa VetMed",
    company: "VetMed Logistics",
    phone: "987-654-3210",
    email: "lisa@vetmed.com",
    address: "456 Oak Ave, Greenfield",
  },
];
// mockData.js
export const patients = [
  {
    id: 1,
    name: "Bella",
    species: "Dog",
    breed: "Labrador",
    petCode: "D123",
    sex: "Female",
    ownerName: "John Doe",
    ownerContact: "555-1234",
    lastAppointment: "2025-04-15",
    nextAppointment: "2025-06-20",
  },
  {
    id: 2,
    name: "Mittens",
    species: "Cat",
    breed: "Siamese",
    petCode: "C987",
    sex: "Male",
    ownerName: "Lisa Smith",
    ownerContact: "555-5678",
    lastAppointment: "2025-05-01",
    nextAppointment: null,
  },
];
export const clients = [
  {
    id: 1,
    owner1: "Jane Doe",
    owner2: "John Doe",
    address: "123 Main St, Springfield",
    contact: "9876543210",
    email: "jane@example.com",
    additionalInfo: {
      petName: "Charlie",
      species: "Dog",
      breed: "Golden Retriever",
      age: "4 years",
      vaccinationStatus: "Up to date",
      notes: "Allergic to chicken",
    },
  },
  {
    id: 2,
    owner1: "Alice Smith",
    owner2: "Bob Smith",
    address: "456 Elm St, Shelbyville",
    contact: "9123456780",
    email: "alice@example.com",
    additionalInfo: {
      petName: "Whiskers",
      species: "Cat",
      breed: "Siamese",
      age: "2 years",
      vaccinationStatus: "Due",
      notes: "Prefers soft food",
    },
  },
];
// mockData.js

export const medicinesMock = [
  {
    id: 1,
    name: "Amoxicillin 250mg",
    type: "Tablet",
    unitName: "milligrams",
    unit: 100,
    price: 50,
    profit: 10,
    expiryDate: "2025-12-31",
    manufactureDate: "2024-01-01",
    supplier: "HealthSupplies Ltd.",
  },
  {
    id: 2,
    name: "Cough Syrup",
    type: "Syrup",
    unitName: "millilitres",
    unit: 50,
    price: 120,
    profit: 25,
    expiryDate: "2026-05-20",
    manufactureDate: "2024-03-15",
    supplier: "MedPharma",
  },
  // add more mock medicines as needed
];

export const expiredMedicines = [
  {
    id: 1,
    name: "Amoxicillin 250mg",
    category: "Medication",
    expiryDate: "2024-11-30",
    quantity: 42,
    unit: "tablets",
    sellingPrice: 3.5,
  },
  {
    id: 2,
    name: "Rabies Vaccine",
    category: "Vaccine",
    expiryDate: "2024-04-30",
    quantity: 18,
    unit: "vials",
    sellingPrice: 25.0,
  },
  {
    id: 3,
    name: "Surgical Gloves (Medium)",
    category: "Surgical Item",
    expiryDate: "2025-03-31",
    quantity: 3,
    unit: "boxes",
    sellingPrice: 18.0,
  },
  {
    id: 4,
    name: "Dog Food (Premium)",
    category: "Food",
    expiryDate: "2024-06-30",
    quantity: 0,
    unit: "bags",
    sellingPrice: 65.0,
  },
];
